In [1]:
import pickle
import jax
import jax.numpy as jnp

In [2]:
url = "./edm-cifar10-32x32-uncond-vp.pkl"

with open(url, "rb") as f:
    net = pickle.load(f)

/home/djfelrl11/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
net.keys()
net['ema'].parameters()

<generator object Module.parameters at 0x7eff3319a040>

In [4]:
for name, params in net['ema'].named_parameters():
    # print(name)
    if "32x32_conv" in name:
        print(name)
        print(params.data.permute(2, 3, 1, 0))
        print(params.data.permute(2, 3, 1, 0).shape)
        print()
        break
    # print(params)
    # if input() == ".":
    #     break      

model.enc.32x32_conv.weight
tensor([[[[ 0.0383,  0.0600,  0.0231,  ...,  0.0898, -0.0308, -0.0521],
          [ 0.1773, -0.0993, -0.0464,  ...,  0.0443, -0.0330,  0.1241],
          [ 0.0629, -0.1381, -0.2838,  ..., -0.2538,  0.0723,  0.0818]],

         [[-0.0375,  0.2537, -0.2562,  ...,  0.1141, -0.0461, -0.4239],
          [ 0.4320, -0.2542, -0.1735,  ..., -0.0800,  0.0096, -0.2441],
          [ 0.3605, -0.2470, -0.1909,  ..., -0.6011, -0.1073, -0.0910]],

         [[-0.3252,  0.1951, -0.2357,  ..., -0.1250,  0.0429, -0.1421],
          [-0.1491, -0.1782,  0.0257,  ..., -0.0295,  0.0707, -0.1429],
          [-0.0355, -0.3586,  0.1748,  ..., -0.3312,  0.0038, -0.0127]]],


        [[[ 0.4675, -0.0102,  0.3828,  ...,  0.2982, -0.1866, -0.2073],
          [ 0.7167,  0.1763, -0.0081,  ..., -0.0347, -0.1040,  0.0323],
          [ 0.3012,  0.3947, -0.2435,  ..., -0.5745,  0.0694, -0.0913]],

         [[ 0.7642, -0.2769, -0.2717,  ...,  0.3505, -0.2819,  0.6648],
          [ 0.0681, -1.588

In [5]:
import sys
sys.path.append("../diffusion/")

In [6]:
import os
from hydra import initialize, initialize_config_module, initialize_config_dir, compose
from omegaconf import OmegaConf
from framework.unifying_framework import UnifyingFramework

In [7]:
with initialize(version_base=None, config_path="../diffusion/configs/"):
    cfg = compose(config_name="config")
    print(cfg)

{'framework': {'diffusion': {'type': 'edm', 'beta': [0.0001, 0.02], 'n_timestep': 18, 'loss': 'l2', 'noise_schedule': 'linear', 'learn_sigma': False, 'sigma_min': 0.002, 'sigma_max': 80, 'rho': 7, 'deterministic_sampling': True, 'S_churn': 30, 'S_min': 0.01, 'S_max': 1, 'S_noise': 1.007, 'train': {'learning_rate': 0.001, 'warmup': 19532, 'batch_size': 512, 'total_step': 400000, 'sampling_step': 10000, 'saving_step': 100000, 'optimizer': {'type': 'Adam'}}}, 'train_idx': 2}, 'model': {'autoencoder': {'image_channels': 3, 'n_channels': 128, 'ch_mults': [1, 2], 'is_atten': [False, False], 'n_blocks': 2, 'dropout_rate': 0.0, 'n_heads': 1, 'n_groups': 32, 'embed_dim': 4}, 'discriminator': {'disc_start': 50001, 'kl_weight': 1e-06, 'disc_weight': 0.5}, 'diffusion': {'type': 'unetpp', 'image_channels': 3, 'n_channels': 128, 'label_dim': 0, 'augment_dim': 9, 'ch_mults': [2, 2, 2], 'is_atten': [False, True, False], 'n_blocks': 4, 'n_heads': 1, 'n_groups': 32, 'dropout_rate': 0.13, 'label_dropout_

/home/djfelrl11/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)


In [8]:
config=cfg
rng = jax.random.PRNGKey(config.rand_seed)
model_type = config.type
diffusion_framework = UnifyingFramework(model_type, config, rng)

Checkpoint 0 loaded


In [9]:
diffusion_framework.framework.model_state.params['UNetpp_0'].keys()

frozen_dict_keys(['dec_16x16_block0', 'dec_16x16_block1', 'dec_16x16_block2', 'dec_16x16_block3', 'dec_16x16_block4', 'dec_16x16_up', 'dec_32x32_aux_conv', 'dec_32x32_aux_norm', 'dec_32x32_block0', 'dec_32x32_block1', 'dec_32x32_block2', 'dec_32x32_block3', 'dec_32x32_block4', 'dec_32x32_up', 'dec_8x8_block0', 'dec_8x8_block1', 'dec_8x8_block2', 'dec_8x8_block3', 'dec_8x8_block4', 'dec_8x8_in0', 'dec_8x8_in1', 'enc_16x16_block0', 'enc_16x16_block1', 'enc_16x16_block2', 'enc_16x16_block3', 'enc_16x16_down', 'enc_32x32_block0', 'enc_32x32_block1', 'enc_32x32_block2', 'enc_32x32_block3', 'enc_32x32_conv', 'enc_8x8_block0', 'enc_8x8_block1', 'enc_8x8_block2', 'enc_8x8_block3', 'enc_8x8_down', 'map_augment', 'map_layer0', 'map_layer1'])

In [10]:
for name, params in net['ema'].named_parameters():
    break
    print(name)
    split_name = name.split(".")
    print(split_name)
    
    if "enc" in split_name:
        print() 

    if input() == ".":
        break
    # print(params)
    # if input() == ".":
    #     break

In [11]:
from flax.traverse_util import flatten_dict, unflatten_dict
def pytorch_keys_to_flax_keys(pytorch_state_dict):
  """
    Input: pytorch state_dict
      The keys of pytorch state_dict consists of 
        `first_stage_model.encoder.conv_in.weight`, for example.
    
    Output: flax frozen_dict
      The keys are converted to
        `['first_stage_model']['encoder']['conv_in']['kernel'] (all `weight` is converted to `kernel`.)
      Values will be the same, except for some transposes.

    Weight of convolutional layers
      pytorch: [out_channel, in_channel, kernel_h, kernel_w]
      flax: [kernel_h, kernel_w, in_channel, out_channel]
  """
  flax_tree = {}
  for tup in pytorch_state_dict:
    flax_key_flatten = tuple(tup.split("."))
    flax_value = jnp.array(pytorch_state_dict[tup])
    flax_tree[flax_key_flatten] = flax_value
  
  flax_tree_unflattened = unflatten_dict(flax_tree)
  return flax_tree_unflattened

In [12]:
flax_dict = pytorch_keys_to_flax_keys(net['ema'].state_dict())
flax_dict_flattened = flatten_dict(flax_dict['model'])

In [13]:
from flax.core import unfreeze, freeze
from flax.jax_utils import unreplicate

params= unreplicate(diffusion_framework.framework.model_state)
params_unfreeze = unfreeze(flatten_dict(params.params))
non_changing_els = ["map_layer0", "map_layer1", "map_augment"]
total_weight = list(flax_dict_flattened.keys())

for k, v in params_unfreeze.items():
  # print(k)
  # input()
  k_ = tuple()
  
  for el in k:
    if el == "UNetpp_0":
      continue
    elif el == "atten":
      continue
    elif 'enc' in el or 'dec' in el:
      tmp_el = el.split("_")
      el = (tmp_el[0], "_".join(tmp_el[1:]),)
    elif el not in non_changing_els:
      el = tuple(el.split("_"))
    else:
      el = (el,)

    if el == ("kernel",) or el == ("scale",):
      k_ += ("weight",)
    else:
      k_ += el

  if k_ in flax_dict_flattened.keys():
    pytorch_dict_value = flax_dict_flattened[k_]
    if len(v.shape) == 4:
      pytorch_dict_value_transposed = jnp.transpose(pytorch_dict_value, (2, 3, 1, 0))
      assert v.shape == pytorch_dict_value_transposed.shape
      params_unfreeze[k] = pytorch_dict_value_transposed
      # print("transferred", flush=True)
    elif len(v.shape) == 1:
      assert v.shape == pytorch_dict_value.shape
      params_unfreeze[k] = pytorch_dict_value
      # print("transferred", flush=True)
    elif len(v.shape) == 2:
      pytorch_dict_value_transposed = jnp.transpose(pytorch_dict_value, (1, 0))
      assert v.shape == pytorch_dict_value_transposed.shape
      params_unfreeze[k] = pytorch_dict_value_transposed
    else:
      print(v.shape)
      raise ValueError("Exist?")
    print(f"{'.'.join(k_)} transferred.")
    total_weight.remove(k_)
  else:
    print()
    raise ValueError(f"{'.'.join(k_)} is not existed in pytorch model")

print(f"{total_weight} of weights remained.")
print("Done")

dec.16x16_block0.affine.bias transferred.
dec.16x16_block0.affine.weight transferred.
dec.16x16_block0.conv0.bias transferred.
dec.16x16_block0.conv0.weight transferred.
dec.16x16_block0.conv1.bias transferred.
dec.16x16_block0.conv1.weight transferred.
dec.16x16_block0.norm0.bias transferred.
dec.16x16_block0.norm0.weight transferred.
dec.16x16_block0.norm1.bias transferred.
dec.16x16_block0.norm1.weight transferred.
dec.16x16_block0.skip.bias transferred.
dec.16x16_block0.skip.weight transferred.
dec.16x16_block1.affine.bias transferred.
dec.16x16_block1.affine.weight transferred.
dec.16x16_block1.conv0.bias transferred.
dec.16x16_block1.conv0.weight transferred.
dec.16x16_block1.conv1.bias transferred.
dec.16x16_block1.conv1.weight transferred.
dec.16x16_block1.norm0.bias transferred.
dec.16x16_block1.norm0.weight transferred.
dec.16x16_block1.norm1.bias transferred.
dec.16x16_block1.norm1.weight transferred.
dec.16x16_block1.skip.bias transferred.
dec.16x16_block1.skip.weight trans

In [14]:
# params_unfreeze[]

In [15]:
for key in total_weight:
    pytorch_dict_value = flax_dict_flattened[key]
    print(key)
    print(pytorch_dict_value.shape)
    print(pytorch_dict_value)

('enc', '16x16_down', 'conv0', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('enc', '16x16_down', 'skip', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('enc', '8x8_down', 'conv0', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('enc', '8x8_down', 'skip', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('dec', '16x16_up', 'conv0', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('dec', '16x16_up', 'skip', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('dec', '32x32_up', 'conv0', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]
('dec', '32x32_up', 'skip', 'resample_filter')
(1, 1, 2, 2)
[[[[0.25 0.25]
   [0.25 0.25]]]]


In [16]:
params_freeze = freeze(unflatten_dict(params_unfreeze))
new_state = unreplicate(diffusion_framework.framework.model_state)
new_state = new_state.replace(params_ema=params_freeze)
new_state = new_state.replace(params=params_freeze)

In [17]:
from flax.training import checkpoints
checkpoints.save_checkpoint(".", new_state, 0, overwrite=True)

'./checkpoint_0'

In [18]:
# flax_dict_flattened[('enc', '32x32_conv', 'weight')].transpose(1, 0, 2, 3)
flax_dict_flattened[('enc', '32x32_conv', 'weight')].shape

(128, 3, 3, 3)

In [19]:
params_freeze['UNetpp_0']['enc_32x32_conv']['weight'].shape
params_freeze['UNetpp_0']['enc_32x32_conv']['weight']
# params_freeze['UNetpp_0'].keys()

Array([[[[ 0.03828168,  0.06004289,  0.02312655, ...,  0.08975515,
          -0.03079157, -0.05214899],
         [ 0.17726456, -0.099301  , -0.04637972, ...,  0.04428555,
          -0.03303021,  0.12414239],
         [ 0.06285588, -0.13811347, -0.28377378, ..., -0.25381586,
           0.07231837,  0.081753  ]],

        [[-0.03752021,  0.25367603, -0.25618958, ...,  0.11411095,
          -0.0461234 , -0.42390025],
         [ 0.43203157, -0.25416735, -0.17350987, ..., -0.07997738,
           0.0096081 , -0.2440669 ],
         [ 0.36049223, -0.24701966, -0.19088207, ..., -0.6011314 ,
          -0.10726789, -0.091041  ]],

        [[-0.3252467 ,  0.19510251, -0.23572196, ..., -0.12497745,
           0.04286664, -0.14211504],
         [-0.1490635 , -0.17821302,  0.02569932, ..., -0.02951242,
           0.07066312, -0.14288044],
         [-0.03545241, -0.358608  ,  0.17481224, ..., -0.33122206,
           0.00377374, -0.01273975]]],


       [[[ 0.46754178, -0.01022834,  0.3828126 , ...,  0